# Generated by Django 2.2.16 on 2022-08-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
